trigger:
- master

pool:
  vmImage: 'windows-2019'


steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest
      source ./emsdk_env.sh
      cd ..
      git clone https://github.com/effekseer/Effekseer --depth 1 ../Effekseer
      python -m pip install dukpy jsmin
      python build.py on_ci

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      python -m pip install --upgrade pip
      pip install selenium chromedriver-binary==76.0.3809.68.0
      cd tests
      python test.py

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Release'
    ArtifactName: 'Release'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'tests/screenshots'
    ArtifactName: 'screenshots'
    publishLocation: 'Container'